In [3]:
import numpy as np
n=np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,9) #two-dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3,3,3) #three-dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m=np.asarray([1,2,3,5])
m

array([1, 2, 3, 5])

### Convert image to Numpy Arrays

In [8]:
import cv2

In [10]:
im_g=cv2.imread("smallgray.png",0) #0--read in grey scale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
im_g=cv2.imread("smallgray.png",1) #1--three layers for three colors
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
cv2.imwrite("newsmallgrey.png",im_g) #create an image

True

### Indexing, Slicing, and Iterating Numpy array

In [13]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
#Indexing and slicing
im_g[0:2,2:4] #row, column

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
im_g.shape

(3, 5)

In [17]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [18]:
#Interating numpy array
for i in im_g: #iterate rows
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
for i in im_g.T: #iterate columns
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [20]:
for i in im_g.flat: #iterate one by one
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


### Stacking and Splitting numpy arrays

In [29]:
ims1=np.hstack((im_g,im_g)) #stack horizontaly

In [30]:
ims1

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [33]:
ims2=np.vstack((im_g,im_g)) #stack vertically
ims2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
lst=np.hsplit(ims1,2) #split horizontaly

In [32]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [34]:
lst2=np.vsplit(ims2,2) #split vertically
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]